# Generated by Django 4.1.1 on 2023-02-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("age", models.IntegerField(default=0, verbose_name="Edad")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                ("phone", models.CharField(max_length=100, verbose_name="Telefono")),
            ],
        ),
    ]
